name: Check preitter format.
on: push

jobs:
  run_prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node Modules ðŸ“¦
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn
          cache-dependency-path: './yarn.lock'

      - name: yarn install
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --prefer-offline

      - name: Run prettier
        run: |
          yarn prettier --check .
